### ISSUE TITLE
Check failed after rbs 3.4.2 released

### ISSUE THREAD

**Issue by elct9620** [soutaro/steep#1026]
I got this error `Cannot find type definitions for library: rbs (3.4.1)` in GitHub Actions

> The workaround to fix it is to run `rbs collection update` to ensure rbs is 3.4.2

The workflow config is:

```yaml
name: CI

on:
  push:
    paths:
      - '.github/workflows/main.yml'
      - 'lib/**'
      - 'sig/**'
      - '*.gemspec'
      - 'spec/**'
      - 'Rakefile'
      - 'Gemfile'
      - 'Steepfile'
      - 'rbs_collection.lock.yaml'
      - '.rubocop.yml'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 4 * * *'
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.1'
          - '3.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Bootstrap RBS
      run: bundle exec rbs collection install
    - name: Run all tests
      run: bundle exec rake
```
