### ISSUE TITLE
Create a Github Action for Steep

### ISSUE THREAD

**Issue by Lykos** [soutaro/steep#298]
It would be cool if you could run Steep checks as part of Github actions.

**Comment by bohdan-sviripa** [comment]
Hey @Lykos 
I was researching steep and came across your issue. I checked out what github actions provide and it seems like you don't really need a standalone github action to run steep checks in your ruby project. 

All you need is to include a single line statement to your actions workflow. Here's an example:

```yaml
jobs:
  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec steep check
```
