### ISSUE TITLE
steep 1.4.0 gets Ruby::UnexpectedError with rdoc directive comments

### ISSUE THREAD

**Issue by halostatue** [soutaro/steep#772]
The errors here can be seen in [KineticCafe/app_identity@rbs-signatures](https://github.com/KineticCafe/app_identity/tree/rbs-signatures), and the errors are in [ruby/steep_expectations.yml](https://github.com/KineticCafe/app_identity/blob/rbs-signatures/ruby/steep_expectations.yml).

I’m seeing multiple instances of various errors with the parsing of rdoc directives like `# :nodoc:` (see [ruby/lib/app_identity/app.rb:15](https://github.com/KineticCafe/app_identity/blob/rbs-signatures/ruby/lib/app_identity/app.rb#L15) for an example).

The error messages are like:

- UnexpectedError: wrong number of arguments (given 0, expected 3)
- UnexpectedError: Unknown alias name: ::nodoc

These seem to be causing *other* problems in some cases (see [ruby/lib/app_identity/app.rb:165-166](https://github.com/KineticCafe/app_identity/blob/rbs-signatures/ruby/lib/app_identity/app.rb#L165-166)), which results in 

- Method parameters are incompatible with declaration `(*untyped, **untyped) -> ::String`
- Unsupported splat node occurrence

The `to_json` method is explicitly suppressed from documentation by `# :nodoc:`.

I’m working with a newer library for experimenting with RBS and steep before I start looking at RBS for my more well-established libraries. I’ve already determined that Sorbet is wholly unsuitable for my libraries through previous experimentation.

**Comment by halostatue** [comment]
I believe that this error is also caused by `# :nodoc:`:

```yaml
- file: lib/app_identity/internal.rb
  diagnostics:
  - range:
      start:
        line: 7
        character: 0
      end:
        line: 130
        character: 3
    severity: ERROR
    message: |-
      UnexpectedError: undefined method `name' for #<Parser::Source::Map:0x0000000107956fc0 @expression=#<Parser::Source::Range lib/app_identity/internal.rb 121...152>, @node=s(:assertion,
        s(:const,
          s(:const, nil, :AppIdentity), :Internal), #<Steep::AST::Node::TypeAssertion:0x0000000107976758 @location=#<RBS::Location:44720 buffer=lib/app_identity/internal.rb, start=7:30, pos=145...152, children= source=':nodoc:'>>)>

                super(node: node, location: node.loc.name)
                                                    ^^^^^
    code: Ruby::UnexpectedError
```
