### ISSUE TITLE
steep 1.4.0 reports incompatible assignment on a constant that matches

### ISSUE THREAD

**Issue by halostatue** [soutaro/steep#773]
The errors here can be seen in [KineticCafe/app_identity@rbs-signatures](https://github.com/KineticCafe/app_identity/tree/rbs-signatures), and the errors are in [ruby/steep_expectations.yml](https://github.com/KineticCafe/app_identity/blob/rbs-signatures/ruby/steep_expectations.yml).

I have some constants in `AppIdentity` defined as:

```rbs
  VERSION: String
  NAME: String
  SPEC_VERSION: Integer
  INFO: {name: String, version: String, spec_version: Integer}
```

When assigning to `INFO` from `VERSION`, `NAME`, and `SPEC_VERSION` (see [ruby/lib/app_identity.rb:22-33](https://github.com/KineticCafe/app_identity/blob/rbs-signatures/ruby/lib/app_identity.rb#L22-L33), I am getting an incompatible assignment error, below:

```yaml
- file: lib/app_identity.rb
  diagnostics:
  - range:
      start:
        line: 32
        character: 2
      end:
        line: 32
        character: 74
    severity: ERROR
    message: |-
      Cannot assign a value of type `::Hash[::Symbol, (::String | ::Integer)]` to a constant of type `{ :name => ::String, :spec_version => ::Integer, :version => ::String }`
        ::Hash[::Symbol, (::String | ::Integer)] <: { :name => ::String, :spec_version => ::Integer, :version => ::String }
    code: Ruby::IncompatibleAssignment
```

I understand *why* the error is happening, but I cannot figure out how I should fix it without losing specificity (that is, I think I can do `{ (:name | :spec_version | :version) => (String | Integer) }`, but that’s not *quite* correct.
