### ISSUE TITLE
 expand_block_given: doesn't satisfy the constraints Interface::Block

### ISSUE THREAD

**Issue by moskvin** [soutaro/steep#885]
The following check 
```
bundle exec steep check
```
gives the error:

```
steep-1.5.1/sig/steep/subtyping/check.rbs:100:44: [error] Type application of `::Steep::Subtyping::Relation` doesn't satisfy the constraints: (::Steep::Interface::Block | nil) <: ::Object
│ Diagnostic ID: RBS::UnsatisfiableTypeApplication
│
└       def expand_block_given: (Symbol name, Relation[Interface::Block?] relation) -> (Relation[Interface::Block] | true | Result::Failure)
```

Ruby 3.2.2
Uses rbs collections (rbs_collection.lock.yaml):
```
sources:
- type: git
  name: ruby/gem_rbs_collection
  revision: aeede7258d020bfd509541e0c8075ce833292409
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
...
```
rbs_collection.yaml:
```yaml
# Download sources
sources:
  - type: git
    name: ruby/gem_rbs_collection
    remote: https://github.com/ruby/gem_rbs_collection.git
    revision: main
    repo_dir: gems

# You can specify local directories as sources also.
# - type: local
#   path: path/to/your/local/repository

# A directory to install the downloaded RBSs
path: .gem_rbs_collection

gems:
  # Skip loading rbs gem's RBS.
  # It's unnecessary if you don't use rbs as a library.
  - name: rbs
    ignore: true
```
